# Default values for the Helm chart

backend:
  image: shreybatra/sample-backend
  replicaCount: 1
  redisUri: redis://redis-svc:6379
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  replicaCount: 1
  backendUrl: http://backend-svc:8000
  service:
    type: NodePort
    port: 5175
    nodePort: 31000

redis:
  image: redis
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

